#!/usr/bin/env bash

# █▀ █▀▀ █▀█ █ █ █ █▀▀ █▀▀ █▀
# ▄█ ██▄ █▀▄ ▀▄▀ █ █▄▄ ██▄ ▄█

# Removable Media Automounter
udiskie &

# Wallpaper
hyprpaper &
# swww-daemon --format xrgb &

# Random Wallpaper
sleep 0.4 && $HOME/.config/hypr/scripts/random_wallpaper &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Filter
hyprsunset &

# Filter Automation
sleep 0.4 && $HOME/.config/hypr/scripts/sunset &

# Notify connecting & disconnecting devices
# devify &

# Screen Lock Idle Daemon
hypridle &

# Trackpad gestures
libinput-gestures &

# Clipboard
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Polkit Authentication
systemctl --user start hyprpolkitagent &
# /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Screen sharing & Portals
$HOME/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Audio
easyeffects --gapplication-service &

# Power Saving
brightnessctl s 2% &

# Sync
# syncthing -no-browser &
