#!/usr/bin/env bash

# Automounter for removable media
udiskie &

# Wallpaper Backend
hyprpaper &
# swww-daemon --format xrgb &

# Pyprland Daemon
pypr --debug /tmp/pypr.log &

# Notification Daemon
swaync &

# OSD Window
swayosd-server &

# Notify about devices connecting and disconnecting
# devify &

# Idle daemon to screen lock
hypridle &

# Trackpad gestures
libinput-gestures &

# Clipboard
wl-paste --type text --watch cliphist store &
wl-paste --type image --watch cliphist store &

# Polkit authentication
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# Screen sharing and portals
$HOME/.config/hypr/scripts/portal &
# xwaylandvideobridge & # Off when using Vesktop instead of Discord

# Audio
easyeffects --gapplication-service &

# Random Wallpaper
$HOME/.config/hypr/scripts/random_wallpaper &

# Brightness Power Saving
brightnessctl s 2% &
